[package]
name = "rustrait-core"
version = "0.0.0"
edition.workspace = true

[dependencies]
prost = "0.13.1"
serde_yaml = "0.9.34"
serde_json = "1.0.120"
substrait = { version = "0.38.0", features = ["serde"] }
