[package]
name = "rustrait"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.13.1"
serde_yaml = "0.9.34"
serde_json = "1.0.120"
substrait = { version = "0.38.0", features = ["serde"] }
